services:
  db:
    image: mysql:8.0
    container_name: kanban-db
    healthcheck:
      # Usamos las variables para que el ping funcione con las credenciales del .env
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "--password=${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - kanban-network

  backend-api:
    build: ./backend
    container_name: kanban-backend
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - kanban-network

  frontend-flask:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend-api
    environment:
      - BACKEND_URL=http://backend-api:5000
      - SECRET_KEY=${SECRET_KEY} # El front también suele necesitarla para las cookies de sesión
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge