server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # 1. Rutas del FRONTEND (Flask Puerto 8080)
    # Cubre /, /auth, /dashboard y /logout
    location / {
        proxy_pass http://kanban-frontend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Rutas del BACKEND API (Flask Puerto 5000)
    # Para que el fetch del Dashboard funcione directamente
    location /tasks {
        proxy_pass http://kanban-backend:5000/tasks;
        proxy_set_header Host $host;
    }

    # Esta es la ruta que usa tu frontend internamente para validar
    location /login {
        proxy_pass http://kanban-backend:5000/login;
        proxy_set_header Host $host;
    }

    location /debug/users {
        proxy_pass http://kanban-backend:5000/debug/users;
        proxy_set_header Host $host;
    }
}